version: '2'
services:
  elasticsearch:
    build: ./elastic
    ports:
     - "9300:9300"
     - "9200:9200"
  kibana:
    build: ./kibana
    ports:
     - "5601:5601"
    links:
     - elasticsearch
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
